<a href="https://colab.research.google.com/github/Kavivisnhu/ml-projects/blob/main/homeloanapproval.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [38]:
import pandas as pd
import numpy as np

In [39]:
df=pd.read_csv('/content/loan_data.csv')

In [40]:
df

,person_age,person_gender,person_education,person_income,person_emp_exp,person_home_ownership,loan_amnt,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file,loan_status
0,22.0,female,Master,71948.0,0,RENT,35000.0,PERSONAL,16.02,0.49,3.0,561,No,1
1,21.0,female,High School,12282.0,0,OWN,1000.0,EDUCATION,11.14,0.08,2.0,504,Yes,0
2,25.0,female,High School,12438.0,3,MORTGAGE,5500.0,MEDICAL,12.87,0.44,3.0,635,No,1
3,23.0,female,Bachelor,79753.0,0,RENT,35000.0,MEDICAL,15.23,0.44,2.0,675,No,1
4,24.0,male,Master,66135.0,1,RENT,35000.0,MEDICAL,14.27,0.53,4.0,586,No,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44995,27.0,male,Associate,47971.0,6,RENT,15000.0,MEDICAL,15.66,0.31,3.0,645,No,1
44996,37.0,female,Associate,65800.0,17,RENT,9000.0,HOMEIMPROVEMENT,14.07,0.14,11.0,621,No,1
44997,33.0,male,Associate,56942.0,7,RENT,2771.0,DEBTCONSOLIDATION,10.02,0.05,10.0,668,No,1
44998,29.0,male,Bachelor,33164.0,4,RENT,12000.0,EDUCATION,13.23,0.36,6.0,604,No,1
44999,24.0,male,High School,51609.0,1,RENT,6665.0,DEBTCONSOLIDATION,17.05,0.13,3.0,628,No,1

In [41]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['person_gender']=le.fit_transform(df['person_gender'])
df['person_education']=le.fit_transform(df['person_education'])
df['person_home_ownership']=le.fit_transform(df['person_home_ownership'])
df['loan_intent']=le.fit_transform(df['loan_intent'])
df['previous_loan_defaults_on_file']=le.fit_transform(df['previous_loan_defaults_on_file'])

In [42]:
df

,person_age,person_gender,person_education,person_income,person_emp_exp,person_home_ownership,loan_amnt,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file,loan_status
0,22.0,0,4,71948.0,0,3,35000.0,4,16.02,0.49,3.0,561,0,1
1,21.0,0,3,12282.0,0,2,1000.0,1,11.14,0.08,2.0,504,1,0
2,25.0,0,3,12438.0,3,0,5500.0,3,12.87,0.44,3.0,635,0,1
3,23.0,0,1,79753.0,0,3,35000.0,3,15.23,0.44,2.0,675,0,1
4,24.0,1,4,66135.0,1,3,35000.0,3,14.27,0.53,4.0,586,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44995,27.0,1,0,47971.0,6,3,15000.0,3,15.66,0.31,3.0,645,0,1
44996,37.0,0,0,65800.0,17,3,9000.0,2,14.07,0.14,11.0,621,0,1
44997,33.0,1,0,56942.0,7,3,2771.0,0,10.02,0.05,10.0,668,0,1
44998,29.0,1,1,33164.0,4,3,12000.0,1,13.23,0.36,6.0,604,0,1
44999,24.0,1,3,51609.0,1,3,6665.0,0,17.05,0.13,3.0,628,0,1

In [43]:
df.isnull().sum()

person_age                        0
person_gender                     0
person_education                  0
person_income                     0
person_emp_exp                    0
person_home_ownership             0
loan_amnt                         0
loan_intent                       0
loan_int_rate                     0
loan_percent_income               0
cb_person_cred_hist_length        0
credit_score                      0
previous_loan_defaults_on_file    0
loan_status                       0
dtype: int64

In [44]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
df['person_age']=sc.fit_transform(df[['person_age']])
df['person_income']=sc.fit_transform(df[['person_income']])
df['person_emp_exp']=sc.fit_transform(df[['person_emp_exp']])
df['loan_amnt']=sc.fit_transform(df[['loan_amnt']])
df['loan_int_rate']=sc.fit_transform(df[['loan_int_rate']])
df['cb_person_cred_hist_length']=sc.fit_transform(df[['cb_person_cred_hist_length']])
df['credit_score']=sc.fit_transform(df[['credit_score']])

In [45]:
df

,person_age,person_gender,person_education,person_income,person_emp_exp,person_home_ownership,loan_amnt,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file,loan_status
0,-0.953538,0,4,-0.104090,-0.892284,3,4.024953,4,1.683039,0.49,-0.739109,-1.419814,0,1
1,-1.118963,0,3,-0.846005,-0.892284,2,-1.359209,1,0.044782,0.08,-0.996863,-2.549975,1,0
2,-0.457264,0,3,-0.844065,-0.397517,0,-0.646600,3,0.625557,0.44,-0.739109,0.047412,0,1
3,-0.788113,0,1,-0.007039,-0.892284,3,4.024953,3,1.417829,0.44,-0.996863,0.840507,0,1
4,-0.622689,1,4,-0.176371,-0.727362,3,4.024953,3,1.095549,0.53,-0.481354,-0.924130,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44995,-0.126414,1,0,-0.402231,0.097249,3,0.857799,3,1.562184,0.31,-0.739109,0.245686,0,1
44996,1.527834,0,0,-0.180537,1.911393,3,-0.092348,2,1.028407,0.14,1.322928,-0.230171,0,1
44997,0.866135,1,0,-0.290681,0.262171,3,-1.078758,0,-0.331212,0.05,1.065174,0.701716,0,1
44998,0.204436,1,1,-0.586348,-0.232595,3,0.382726,1,0.746412,0.36,0.034155,-0.567237,0,1
44999,-0.622689,1,3,-0.356994,-0.727362,3,-0.462113,0,2.028819,0.13,-0.739109,-0.091380,0,1

In [46]:
x=df.drop('loan_status',axis=1)
y=df['loan_status']

In [47]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [48]:
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression

In [49]:
model=LogisticRegression(solver='liblinear')
rfe=RFE(estimator=model,n_features_to_select=8)
rfe.fit(x_train,y_train)

print('Selected features mask:', rfe.support_)
print('Selected feature names:', x_train.columns[rfe.support_].tolist())
print('Feature ranking:', rfe.ranking_)

# Transform x_train and x_test to include only the selected features
x_train = rfe.transform(x_train)
x_test = rfe.transform(x_test)

Selected features mask: [ True False False False  True  True  True False  True  True False  True
  True]
Selected feature names: ['person_age', 'person_emp_exp', 'person_home_ownership', 'loan_amnt', 'loan_int_rate', 'loan_percent_income', 'credit_score', 'previous_loan_defaults_on_file']
Feature ranking: [1 4 6 5 1 1 1 2 1 1 3 1 1]

In [51]:
selected_features = x.columns[rfe.support_]
print('top 8 features this model')
for feature in selected_features:
  print(feature)

top 8 features this model
person_age
person_emp_exp
person_home_ownership
loan_amnt
loan_int_rate
loan_percent_income
credit_score
previous_loan_defaults_on_file

In [52]:
df.head()

,person_age,person_gender,person_education,person_income,person_emp_exp,person_home_ownership,loan_amnt,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file,loan_status
0,-0.953538,0,4,-0.104090,-0.892284,3,4.024953,4,1.683039,0.49,-0.739109,-1.419814,0,1
1,-1.118963,0,3,-0.846005,-0.892284,2,-1.359209,1,0.044782,0.08,-0.996863,-2.549975,1,0
2,-0.457264,0,3,-0.844065,-0.397517,0,-0.646600,3,0.625557,0.44,-0.739109,0.047412,0,1
3,-0.788113,0,1,-0.007039,-0.892284,3,4.024953,3,1.417829,0.44,-0.996863,0.840507,0,1
4,-0.622689,1,4,-0.176371,-0.727362,3,4.024953,3,1.095549,0.53,-0.481354,-0.924130,0,1

In [53]:
kv=df.drop(['person_gender','person_education','person_income','loan_intent','cb_person_cred_hist_length'], axis=1)

In [54]:
kv

,person_age,person_emp_exp,person_home_ownership,loan_amnt,loan_int_rate,loan_percent_income,credit_score,previous_loan_defaults_on_file,loan_status
0,-0.953538,-0.892284,3,4.024953,1.683039,0.49,-1.419814,0,1
1,-1.118963,-0.892284,2,-1.359209,0.044782,0.08,-2.549975,1,0
2,-0.457264,-0.397517,0,-0.646600,0.625557,0.44,0.047412,0,1
3,-0.788113,-0.892284,3,4.024953,1.417829,0.44,0.840507,0,1
4,-0.622689,-0.727362,3,4.024953,1.095549,0.53,-0.924130,0,1
...,...,...,...,...,...,...,...,...,...
44995,-0.126414,0.097249,3,0.857799,1.562184,0.31,0.245686,0,1
44996,1.527834,1.911393,3,-0.092348,1.028407,0.14,-0.230171,0,1
44997,0.866135,0.262171,3,-1.078758,-0.331212,0.05,0.701716,0,1
44998,0.204436,-0.232595,3,0.382726,0.746412,0.36,-0.567237,0,1
44999,-0.622689,-0.727362,3,-0.462113,2.028819,0.13,-0.091380,0,1

In [55]:
from imblearn.over_sampling import SMOTE
sm=SMOTE()

In [56]:
x_train,y_train=sm.fit_resample(x_train,y_train)

In [57]:
y_train.value_counts()

loan_status
0    28010
1    28010
Name: count, dtype: int64

In [58]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
lr.fit(x_train,y_train)

LogisticRegression()

In [59]:
y_pred=lr.predict(x_test)
y_pred

array([0, 0, 1, ..., 1, 1, 1])

In [60]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.8534444444444444

In [61]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred)

array([[5854, 1136],
       [ 183, 1827]])

In [62]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.97      0.84      0.90      6990
           1       0.62      0.91      0.73      2010

    accuracy                           0.85      9000
   macro avg       0.79      0.87      0.82      9000
weighted avg       0.89      0.85      0.86      9000

In [76]:
# ===== INPUT CODE FOR PREDICTION =====

import numpy as np

# Enter values manually
person_age = int(input("Enter Age: "))
#person_income = float(input("Enter Income: "))
person_emp_exp = int(input("Enter Experience: "))
person_home_ownership = int(input("Enter Home Ownership (0/1/2/3): "))
loan_amnt = float(input("Enter Loan Amount: "))
loan_int_rate = float(input("Enter Interest Rate: "))
loan_percent_income = float(input("Enter Loan Percent Income: "))
#cb_person_cred_hist_length = int(input("Enter Credit History Length: "))
credit_score = int(input("Enter Credit Score: "))
previous_loan_defaults_on_file = int(input("Previous Loan Default (0/1): "))

# Create input array
input_data = np.array([[
    person_age,
    person_emp_exp,
    person_home_ownership,
    loan_amnt,
    loan_int_rate,
    loan_percent_income,
    credit_score,
    previous_loan_defaults_on_file
]])

# Prediction
prediction = lr.predict(input_data)

# Output
if prediction == 1:
    print("approved 1")
else:
    print("notapproval 0")

Enter Age: 22
Enter Experience: 0
Enter Home Ownership (0/1/2/3): 3
Enter Loan Amount: 35000
Enter Interest Rate: 0.49
Enter Loan Percent Income: 3
Enter Credit Score: 560
Previous Loan Default (0/1): 1
notapproval 0